require_relative 'command/base'
require_relative 'command/base_list'
require_relative 'command/base_object'

require_relative 'command/console'
require_relative 'command/inspect'
require_relative 'command/list'
require_relative 'command/show'
require_relative 'command/stats'
require_relative 'command/suggest'

require_relative 'command/options/base'
require_relative 'command/options/base_list'
require_relative 'command/options/base_object'

require_relative 'command/options/console'
require_relative 'command/options/inspect'
require_relative 'command/options/list'
require_relative 'command/options/show'
require_relative 'command/options/stats'
require_relative 'command/options/suggest'

require_relative 'command/output/base'
require_relative 'command/output/console'
require_relative 'command/output/inspect'
require_relative 'command/output/list'
require_relative 'command/output/show'
require_relative 'command/output/stats'
require_relative 'command/output/suggest'
